### ISSUE TITLE
all blue rendering

### ISSUE THREAD

**Issue by Youichi1985** [ollieread/TechnoMagi#29]
when I start up a world with technomagi installed via the curse launcher. all that renders is the tool bar the inventory screen plus the players hand or the held item the entire world appears blue I have tried this with other mods and also with just this mod
this was done with forge 10.13.4.1492 and version 0.6.0.34
![2015-08-27_16 40 44](https://cloud.githubusercontent.com/assets/12457063/9535868/c89b20a4-4cda-11e5-85be-17f78bcdd698.png)
![2015-08-27_16 40 50](https://cloud.githubusercontent.com/assets/12457063/9535870/cb75efd4-4cda-11e5-88d7-8580954de880.png)

I also forced a crash using f3 + c for a crash log in case that had some pertinent information.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 8/27/15 4:36 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Youichikun'/934, l='MpServer', x=150.50, y=70.62, z=258.50]]
	Chunk stats: MultiplayerChunkCache: 558, 558
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (148,64,256), Chunk: (at 4,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 802 game time, 802 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntitySheep['Sheep'/651, l='MpServer', x=189.81, y=72.00, z=266.19], EntitySheep['Sheep'/656, l='MpServer', x=197.50, y=70.00, z=220.50], EntitySheep['Sheep'/657, l='MpServer', x=198.69, y=70.00, z=222.31], EntitySheep['Sheep'/658, l='MpServer', x=192.91, y=68.00, z=223.03], EntityHorse['Horse'/660, l='MpServer', x=199.13, y=68.00, z=230.13], EntityHorse['Horse'/661, l='MpServer', x=199.50, y=68.00, z=231.50], EntityHorse['Horse'/662, l='MpServer', x=199.50, y=68.00, z=228.50], EntitySheep['Sheep'/663, l='MpServer', x=199.25, y=68.00, z=226.81], EntitySheep['Sheep'/668, l='MpServer', x=198.84, y=76.00, z=252.66], EntitySheep['Sheep'/670, l='MpServer', x=194.31, y=69.00, z=259.69], EntitySheep['Sheep'/671, l='MpServer', x=192.75, y=75.00, z=250.16], EntityBat['Bat'/675, l='MpServer', x=188.52, y=19.58, z=318.54], EntityClientPlayerMP['Youichikun'/934, l='MpServer', x=150.50, y=70.62, z=258.50], EntitySheep['Sheep'/680, l='MpServer', x=220.97, y=75.00, z=287.03], EntitySheep['Sheep'/681, l='MpServer', x=223.59, y=75.00, z=284.47], EntitySheep['Sheep'/682, l='MpServer', x=213.97, y=74.00, z=290.06], EntityBat['Bat'/554, l='MpServer', x=74.34, y=59.02, z=198.67], EntityBat['Bat'/555, l='MpServer', x=71.42, y=59.76, z=195.21], EntityBat['Bat'/556, l='MpServer', x=73.52, y=25.46, z=257.75], EntityBat['Bat'/562, l='MpServer', x=88.75, y=13.13, z=311.54], EntitySheep['Sheep'/564, l='MpServer', x=96.50, y=72.00, z=219.50], EntitySheep['Sheep'/692, l='MpServer', x=218.06, y=74.00, z=182.03], EntitySheep['Sheep'/565, l='MpServer', x=91.13, y=65.00, z=226.66], EntitySheep['Sheep'/693, l='MpServer', x=230.44, y=72.00, z=187.34], EntitySheep['Sheep'/566, l='MpServer', x=99.19, y=72.00, z=210.13], EntitySheep['Sheep'/694, l='MpServer', x=228.44, y=72.00, z=186.34], EntitySheep['Sheep'/695, l='MpServer', x=228.50, y=71.00, z=191.50], EntitySheep['Sheep'/568, l='MpServer', x=99.03, y=69.00, z=226.75], EntitySheep['Sheep'/569, l='MpServer', x=106.44, y=69.00, z=287.09], EntitySheep['Sheep'/570, l='MpServer', x=105.34, y=76.00, z=296.47], EntitySheep['Sheep'/700, l='MpServer', x=219.91, y=76.00, z=283.16], EntitySheep['Sheep'/572, l='MpServer', x=118.50, y=70.00, z=186.50], EntitySheep['Sheep'/573, l='MpServer', x=118.50, y=70.00, z=186.50], EntitySheep['Sheep'/574, l='MpServer', x=117.91, y=75.00, z=180.31], EntitySheep['Sheep'/575, l='MpServer', x=114.50, y=70.00, z=190.50], EntitySheep['Sheep'/581, l='MpServer', x=114.50, y=70.00, z=289.50], EntitySheep['Sheep'/582, l='MpServer', x=114.50, y=70.00, z=289.50], EntitySheep['Sheep'/585, l='MpServer', x=124.50, y=73.00, z=335.78], EntitySheep['Sheep'/586, l='MpServer', x=124.50, y=73.00, z=333.22], EntitySheep['Sheep'/587, l='MpServer', x=124.50, y=73.00, z=334.50], EntitySheep['Sheep'/591, l='MpServer', x=127.50, y=73.00, z=337.50], EntityBat['Bat'/604, l='MpServer', x=126.31, y=43.08, z=216.21], EntitySheep['Sheep'/611, l='MpServer', x=149.44, y=69.00, z=236.25], EntitySheep['Sheep'/612, l='MpServer', x=140.59, y=70.00, z=239.27], EntitySheep['Sheep'/613, l='MpServer', x=166.47, y=68.00, z=250.63], EntitySheep['Sheep'/614, l='MpServer', x=145.47, y=69.00, z=239.22], EntityBat['Bat'/618, l='MpServer', x=160.42, y=24.00, z=267.57], EntityBat['Bat'/620, l='MpServer', x=156.63, y=46.16, z=322.58], EntityBat['Bat'/632, l='MpServer', x=147.59, y=22.57, z=278.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 629928392 bytes (600 MB) / 1468006400 bytes (1400 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3584m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAAAAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAAAAAAA	Technomagi{0.6.0.34-alpha} [Technomagi] (Technomagi-0.6.0.34-alpha.jar) 
	UCHIJAAAAAAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAAAAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAAAAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.0' Renderer: 'AMD Radeon R7 200 Series'
	Launched Version: forge-10.13.4.1492
	LWJGL: 2.9.1
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ollieread** [comment]
Oh dear god. I have no idea how that is happening, but I will take a look into it.

**Comment by Youichi1985** [comment]
hope I gave enough info I was afk for a few days but if you need me to do anything for testing let me know.
